mongoSettings:
  databaseName: "doc-system"
  uri: "mongodb://admin:admin@127.0.0.1:27017"
jwtSettings:
  sessionTime: 60
  secretKey: "869eaeb7-cc58-49c6-81ef-691f850bc1c3-d2173906-4d35-4c45-85fd-e7fce81bf12e"